- name: Deploy DevOps Bootstrap Stack
  hosts: bootstrap_stack
  become: true
  
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Apply security hardening
      include_role:
        name: security_hardening

    - name: Deploy multi-service app
      include_role:
        name: deploy_compose_stack