services:
  web:
    image: "nginx:alpine"
    ports:
      - "80:80"
    depends_on:
        back:
            condition: service_started
    networks:
      - app-net

  back:
    build: ../backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: appuser
      DB_PASSWORD: mysecretpassword
      DB_NAME: appdb
    depends_on:
        db:
            condition: service_started
    networks:
      - app-net

  db:
    image: "postgres:alpine"
    restart: always
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net: