- name: Create deployment directory
  file:
    path: /opt/devops-bootstrap/
    state: directory

- name: Copy Docker Compose files
  copy:
    src: files/
    dest: /opt/devops-bootstrap/

- name: Install docker-compose
  apt:
    name: docker-compose
    state: present

- name: Launch docker-compose stack
  shell: docker-compose up -d
  args:
    chdir: /opt/devops-bootstrap/