- name: Create deployment directory
  file:
    path: /opt/devops-bootstrap/
    state: directory

- name: Copy Docker Compose files except Traefik, Docker Compose and Lets Encrypt
  synchronize:
    src: files/
    dest: /opt/devops-bootstrap/
    rsync_opts:
      - "--exclude=traefik.yml"
      - "--exclude=docker-compose-*.yml"
      - "--exclude=letsencrypt/"

- name: Copy correct Docker Compose config
  copy:
    src: "{{ 'docker-compose-https.yml' if use_https | bool else 'docker-compose-http.yml' }}"
    dest: /opt/devops-bootstrap/docker-compose.yml

- name: Copy Traefik config only if HTTPS enabled
  copy:
    src: traefik.yml
    dest : /opt/devops-bootstrap/traefik.yml
  when: use_https | bool

- name: Copy Lets Encrypt only if HTTPS enabled
  copy:
    src: letsencrypt/
    dest : /opt/devops-bootstrap/letsencrypt/
  when: use_https | bool

- name: Set correct permissions on acme.json only if HTTPS enabled
  file:
    path: /opt/devops-bootstrap/letsencrypt/acme.json
    mode: '600'
  when: use_https | bool

- name: Set correct permissions on cert-rerty.sh only if HTTPS enabled
  file:
    path: /opt/devops-bootstrap/scripts/cert-retry.sh
    mode: '740'
  when: use_https | bool

- name: Install docker-compose
  apt:
    name: docker-compose
    state: present

- name: Retry until Traefik ACME cert is OK
  script: ./scripts/cert-retry.sh
  register: cert_retry_output
  when: use_https | bool

- name: Show Cert Retry result
  debug:
    var: cert_retry_output.stdout_lines
  when: use_https | bool

- name: Launch docker-compose stack
  shell: docker-compose up -d
  args:
    chdir: /opt/devops-bootstrap/
  when: not use_https | bool