- name: Install fail2ban
  apt:
    name: fail2ban
    state: present

- name: Copy jail.local
  copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local

- name: Copy custom filter
  copy:
    src: sshd-ec2connect.conf
    dest: /etc/fail2ban/filter.d/sshd-ec2connect.conf

- name: Copy hardened sshd_config
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config

- name: Restart ssh service
  service:
    name: ssh
    state: restarted
    enabled: true

- name: Restart fail2ban service
  service:
    name: fail2ban
    state: restarted
    enabled: true

- name: Copy custom nftables rule script
  copy: 
    src: nft-custom.sh
    dest: /usr/local/bin/nft-custom.sh
    mode: 744

- name: Copy systemd service for nftables rule script
  copy:
    src: nft-custom.service
    dest: /etc/systemd/system/nft-custom.service 

- name: Enable and start custom nftables service
  systemd:
    name: nft-custom.service
    enabled: true
    state: started