services:

  traefik:
    image: traefik
    command:
      - "--configFile=/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik.yml:/traefik.yml:ro
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - app-net

  web:
    build: ./web
    depends_on:
        back:
            condition: service_started
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.web-local.rule=PathPrefix(`/`)"
      - "traefik.http.routers.web-local.entrypoints=web"

      - "traefik.http.routers.web-https.rule=Host(`prodstack.xyz`) && PathPrefix(`/`)"
      - "traefik.http.routers.web-https.entrypoints=websecure"
      - "traefik.http.routers.web-https.tls.certresolver=letsencrypt"
    networks:
      - app-net

  back:
    build: ./use-cases/use-case-node-api
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.api-local.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.api-local.entrypoints=web"

      - "traefik.http.routers.api-https.rule=Host(`prodstack.xyz`) && PathPrefix(`/api`)"
      - "traefik.http.routers.api-https.entrypoints=websecure"
      - "traefik.http.routers.api-https.tls.certresolver=letsencrypt"
    environment:
      DB_HOST: db
      DB_USER: appuser
      DB_PASSWORD: mysecretpassword
      DB_NAME: appdb
    networks:
      - app-net

  db:
    image: "postgres:alpine"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./use-cases/use-case-node-api/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net

  cadvisor:
    image: "gcr.io/cadvisor/cadvisor"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - app-net

  prometheus:
    image: "prom/prometheus"
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.prometheus-local.rule=PathPrefix(`/monitoring`)"
      - "traefik.http.routers.prometheus-local.entrypoints=web"

      - "traefik.http.routers.prometheus-https.rule=Host(`prodstack.xyz`) && PathPrefix(`/monitoring`)"
      - "traefik.http.routers.prometheus-https.entrypoints=websecure"
      - "traefik.http.routers.prometheus-https.tls.certresolver=letsencrypt"

      - "traefik.http.middlewares.strip-monitoring.stripPrefix.prefixes=/monitoring"
      - "traefik.http.routers.prometheus-local.middlewares=strip-monitoring"
      - "traefik.http.routers.prometheus-https.middlewares=strip-monitoring"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net: