name: Deploy with Ansible

on:
  push:
    paths:
      - 'app/**'
      - 'configuration/ansible/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Debug secrets
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} docker -v

      # - name: Run Ansible Playbook
      #   run: 
      #     ansible-playbook configuration/ansible/playbook.yml -i ${{ secrets.EC2_HOST }} -u ${{ secrets.EC2_USER }} --private-key ~/.ssh/id_rsa
